### ISSUE TITLE
Support `<~` and `~`

### ISSUE THREAD

**Issue by ivan-kleshnin** [durkiewicz/elm-plugin#1]
Hi, Kamil. Thank you for your work!

I'd like to see `<~` and `~` operators from

http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Signal

supported. Now they become highlighed as a syntax error.

**Comment by ivan-kleshnin** [comment]
My bad. Those two seem to be deprecated and dropped from the core. Closing.

**Comment by durkiewicz** [comment]
I'll actually re-open this issue, because it makes sense.
The `~` is a valid operator character and it should not be highlighted as a syntax error.

**Comment by ivan-kleshnin** [comment]
:+1:

**Comment by durkiewicz** [comment]
Fixed here: https://github.com/durkiewicz/elm-plugin/commit/8647582b047cdec3919e48bafdd0fb318ff1a863
