### ISSUE TITLE
Exploring contributing: JFlex.jar could not be downloaded

### ISSUE THREAD

**Issue by amcsi** [durkiewicz/elm-plugin#11]
Hey I'm following your steps to try to contribute. I was following your steps, but got stuck at "Open src/org/elmlang/intellijplugin/Elm.flex file and generate lexer code (*)"

I'm getting "Failed to download ..." and it shows a URL that I can't copy, but is supposed to point at this: https://github.com/JetBrains/intellij-community/blob/webstorm/162.104/tools/lexer/jflex-1.4/lib/JFlex.jar
However the link points to the master branch rather than the 162.104 tag, and on that branch the jflex-1.4 directory doesn't exist https://github.com/JetBrains/intellij-community/tree/webstorm/162.374/tools/lexer

How do I get this project properly set up?

**Comment by durkiewicz** [comment]
I had the same issue. It here:

https://github.com/JetBrains/Grammar-Kit/issues/112
