### ISSUE TITLE
port module declaration flagged as error

### ISSUE THREAD

**Issue by fineline** [durkiewicz/elm-plugin#12]
It seems in Elm 0.17 any module that declares a port needs to start like:

`port module MyModule exposing (..)`

This causes the plugin to flag errors on the module keyword

> LOWER_CASE_IDENTIFIER expected, got 'module'

As well as a few other subsequent errors in following lines (eg. on `import`). Removing the initial "port" before "module" removes all errors.

**Comment by durkiewicz** [comment]
It looks like a critical bug. I'll fix it ASAP.

**Comment by fineline** [comment]
Great, thanks (and great work on the plugin BTW)! 

Bit more information, all errors after the `port module` declaration are reported on imports or things that should have been imported, e.g.

```
import Html.App exposing (..)

main = program ({init = init, update = update, view = view, subscriptions = subscriptions})
```

Shows errors on the `import` keyword and the `program` identifier that should have been imported, but not on any of the references to local functions.

**Comment by fineline** [comment]
I tried to isolate these errors out by making a module just for ports, so other modules wouldn't show these other import errors. It does work for most things, but any module that needs to reference a port shows errors on the import of the ports module, and on any reference to anything from that module.

**Comment by fineline** [comment]
Thanks Kamil, works great!
