### ISSUE TITLE
Calls to imported ports are underlined

### ISSUE THREAD

**Issue by fineline** [durkiewicz/elm-plugin#13]
Now that the "port module" declaration is recognised properly no errors show up in that module, and if I import that module in another module, the import itself does not show as an error. But if I put in a call to an outgoing port (i.e. one that returns a Comnmand) or to an incoming port (i.e. one that returns a Subscription) in the other module then the point at which I call the port is underlined, with the error "Cannot find symbol <portname>". Still compiles and runs fine.

If I wrap the calls within functions in the Ports module itself, no errors are reported, either at the port call point (now in the Ports module) or at the point that the imported wrapper function is called.

**Comment by durkiewicz** [comment]
@fineline, Can you please prepare sample code that illustrates this bug? Please make it compilable, so that I can just download it, compile it and see the error.

**Comment by fineline** [comment]
Sure thing, I will create a simpler sample that shows it, give me 24H.

**Comment by fineline** [comment]
@durkiewicz here it is:

https://github.com/fineline/ElmImPort

Thanks for taking a look.
