### ISSUE TITLE
Atom Color Scheme

### ISSUE THREAD

**Issue by douglascorrea** [durkiewicz/elm-plugin#14]
Is there a easy easy to configure the Atom Color Scheme using this plugin?

![Atom](http://f.cl.ly/items/3n3u0y2I1h1T3q1B2k0H/Image%202016-06-21%20at%2011.15.28%20AM.png)

**Comment by klazuka** [comment]
I've been working on [improving the syntax highlighting](https://github.com/klazuka/elm-plugin/tree/better-syntax-highlighting). My plan is to prepare a PR sometime this week. With this change , you would be able to achieve something very similar to the Atom scheme as it will expose the function definition and the type annotation for highlighting.

**Comment by douglascorrea** [comment]
@klazuka good to know, thanks for doing it, tell me if I can help with something.

**Comment by durkiewicz** [comment]
@klazuka, can you please make a PR to the `elm-0.16` branch? (as it is requested in "Contributing" section in the README file) I would like to support both Elm 0.16 and 0.17 for at least several months.

**Comment by klazuka** [comment]
@durkiewicz will do

**Comment by fineline** [comment]
Am I correct that this is not in a release yet? I can't see the settings screen for this.

**Comment by klazuka** [comment]
@fineline correct, it has been merged but not yet released.

**Comment by durkiewicz** [comment]
It's released so I'm closing the issue.
