### ISSUE TITLE
plugin error on valid code

### ISSUE THREAD

**Issue by kjozsa** [durkiewicz/elm-plugin#23]
https://gist.github.com/kjozsa/99110b5a7b369fa8558828224a019e19 - line 7 shows an error in the plugin claiming `LOWER_CASE_IDENTIFIER expected, got '...' ` but I believe this is valid Elm code. 

Thanks!

**Comment by durkiewicz** [comment]
I don't find this bug worth fixing. You shouldn't indent your code like that, should you? If you do find it worth fixing then please reopen the issue and create a pull request.
