### ISSUE TITLE
Incorrect 'cannot find symbol' red underline (because of parsing of unary minus)

### ISSUE THREAD

**Issue by Janiczek** [durkiewicz/elm-plugin#24]
![selection_016](https://cloud.githubusercontent.com/assets/149425/17403704/3902ad76-5a59-11e6-89cd-222bd5b93072.png)

https://github.com/Janiczek/textscape/blob/master/test/frontend/Fuzzers/Possesion.elm#L253

It imports Shrink which contains the given function:
![selection_017](https://cloud.githubusercontent.com/assets/149425/17403764/713b829e-5a59-11e6-9cfc-439e6f84f7b9.png)

![selection_018](https://cloud.githubusercontent.com/assets/149425/17403766/742b4066-5a59-11e6-9efd-0895ab264ac8.png)

https://github.com/elm-community/shrink/blob/master/src/Shrink.elm#L110

Looking there, it seems the error is in `-n` which is valid code but the plugin doesn't see it as such, and then transitively doesn't accept the function, its export and usage in my code.

**Comment by durkiewicz** [comment]
Thanks for reporting it. I will try to fix it when I find some time.
