### ISSUE TITLE
Cannot find module "Css"

### ISSUE THREAD

**Issue by NeverwinterMoon** [durkiewicz/elm-plugin#25]
I am getting this error when using "rtfeldman/elm-css". The dependency is present in elm-package.json and is also installed. Not only that, but I can import some sub-modules of the same dependency without any warnings, but not the root one, so:

`import Css exposing (..)` gives me errors and does not allow any code completion, but

`import Css.Structure exposing (..)` works just fine.

Oh, and project compiles and works just fine. This gives me so much grief right now that I am forced to use Sublime and Atom instead of my all-time favorite IDEA. I would get on my fours and beg for this issue to be addressed and fixed.

The error is being caused by Css module exposing `(.)`. It's totally valid (https://github.com/rtfeldman/elm-css) but I get `LIST_CONSTRUCTORE or OPERATOR expected` error. If remove this from the list of things exposed by Css (or just expose everything), all works just fine.

Exports of Css: https://gyazo.com/1942e17281a432f3b8fdb4aa246862d6

**Comment by durkiewicz** [comment]
Thanks for reporting it. It's surprising to me that dot is a valid custom operator. It will be a bit tricky as I need to differentiate `a.b`, `a . b` and `a .b`. I will do my best to fix it when I find some time.

**Comment by NeverwinterMoon** [comment]
Awesome work, thanks a lot!
