### ISSUE TITLE
Function/code folding

### ISSUE THREAD

**Issue by mordrax** [durkiewicz/elm-plugin#29]
I'm unable to fold functions to their signatures. The menu options are not disabled but they do not have any effect on the code.

![image](https://cloud.githubusercontent.com/assets/4709169/18582681/a033c428-7c49-11e6-9f0f-99e1224b61dd.png)

Since a function name and it's signature are very good at describing what it does, most of the time I do not need to see it's implementation, so ideally, I'd like all functions folded by default!

Love this plugin, is the reason why I went back to webstorm for Elm.

**Comment by durkiewicz** [comment]
I agree that it would be a feature that would be really nice to have.

**Comment by mordrax** [comment]
Folding via elm semantics and syntax might be unnecessarily complex. 

A good 'solution' for those already formatting their code (by hand or elm-format) is to just fold via indentation! This is a generic approach that worked well in sublime text, I was surprised that webstorm didn't offer this out of the box and went searching for a simple 'custom' fold but didn't come up with anything.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
