### ISSUE TITLE
Aliasing a module with same name as another confuses auto-complete

### ISSUE THREAD

**Issue by coreyhaines** [durkiewicz/elm-plugin#30]
So, I often will do this

```
import List.Extra as List
import Maybe.Extra as Maybe
```

to merge the functions into just `List` or `Maybe`
But, this confuses the auto-complete. It appears to only keep the last one imported, and it stops being able to recognize the functions on the previous module. So, if I do this

```
import List.Extra as List
```

then it will stop knowing about things like `List.map` in the auto-complete and also put a red squiggle under `List.map`
I can fix this by doing

```
import List.Extra as List
import List
```

but then it loses track of the functions in List.Extra.

Would be great if aliasing was additive!

**Comment by amcsi** [comment]
Is this even possible in Elm? I'd be surprised, because in less strict languages like PHP and Java you couldn't just import two things with the same name and then just expect there to be a fallback order; you cannot import the same name.

**Comment by coreyhaines** [comment]
Yup, totally possible. It is effectively importing those functions into the same namespace. I find the code looks a lot nicer than having a lot of `List.Extra` floating around.

**Comment by bgourlie** [comment]
That's really interesting.  How does it deal with potential name conflicts?

**Comment by durkiewicz** [comment]
@coreyhaines Please have a look at https://github.com/durkiewicz/elm-plugin/issues/42
