### ISSUE TITLE
effect keyword causing problems with Return.effect

### ISSUE THREAD

**Issue by mateuscb** [durkiewicz/elm-plugin#31]
I started using a package ([Return](http://package.elm-lang.org/packages/Fresheyeball/elm-return/4.0.0/Return#effect)) that has a method called `effect`. I'm not sure what the keyword `effect`  has in Elm, since I have never come across it. But, when ever I call the `Return.effect` it breaks any syntax after it. Is there a way to check if `effect` is used as a method, and if so, allow it. The code compiles with 0.17.1.

**Comment by durkiewicz** [comment]
It does compile but in my opinion it shouldn't: https://github.com/elm-lang/elm-compiler/issues/1518

I've also raised an issue in elm-return for you: https://github.com/Fresheyeball/elm-return/issues/2

You are welcome to comment on these issues.
