### ISSUE TITLE
show actual errors in IntelliJ

### ISSUE THREAD

**Issue by ccapndave** [durkiewicz/elm-plugin#32]
Do I need to set something up to get actual errors displayed, or is this something that isn't possible yet?

For example, is there a way to get this red squiggly underlined?

``` elm
x : Int
x = "Hello"
```

**Comment by bgourlie** [comment]
In order for it to display compile errors, it would need to invoke the compiler and parse the results as you type.  This is something that's not currently implemented AFAIK.

**Comment by durkiewicz** [comment]
Duplicate of https://github.com/durkiewicz/elm-plugin/issues/27
