### ISSUE TITLE
Picks up the wrong definition for Test type of elm-test

### ISSUE THREAD

**Issue by mordrax** [durkiewicz/elm-plugin#33]
webstorm underlines Test and tells me it 'cannot find symbol Test'

![image](https://cloud.githubusercontent.com/assets/4709169/18805138/6eb202e2-8249-11e6-8aec-e0caea7260ff.png)

when I click on the `import Test exposing (..)` line, it takes me to a Test module defined in the "krisajenkins/elm-astar" which doesn't have a definition for Test.
however, what it should take me to is elm-test/Test

elm-package.json

```
{
    "version": "1.0.0",
    "summary": "Sample Elm Test",
    "repository": "https://github.com/user/project.git",
    "license": "BSD-3-Clause",
    "source-directories": [
        ".",
        "../src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-community/elm-test": "2.0.0 <= v < 3.0.0",
        "rtfeldman/node-test-runner": "2.0.0 <= v < 3.0.0",
        "elm-community/list-extra": "3.1.0 <= v < 4.0.0",
        "elm-community/random-extra": "1.0.0 <= v < 2.0.0",
        "elm-lang/core": "4.0.5 <= v < 5.0.0",
        "elm-lang/html": "1.1.0 <= v < 2.0.0",
        "elm-lang/keyboard": "1.0.0 <= v < 2.0.0",
        "elm-lang/mouse": "1.0.0 <= v < 2.0.0",
        "elm-lang/navigation": "1.0.0 <= v < 2.0.0",
        "elm-lang/window": "1.0.0 <= v < 2.0.0",
        "krisajenkins/elm-astar": "2.0.3 <= v < 3.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}
```

**Comment by davidsavoya** [comment]
FYI I am having the same issue in rubymine. Only when I have elm-stuff that is in my test excluded so that it does not show up in search.

**Comment by durkiewicz** [comment]
@mordrax @davidsavoya Please have a look at https://github.com/durkiewicz/elm-plugin/issues/42
