### ISSUE TITLE
Do not suggest the 'add import' quick fix in an import's exposing clause

### ISSUE THREAD

**Issue by klazuka** [durkiewicz/elm-plugin#34]
If you mistype a name in an import's `exposing` clause, the plugin will erroneously suggest that you add an import as if it were a normal expression in your program.

e.g.
<img width="329" alt="screen shot 2016-09-25 at 6 15 35 pm" src="https://cloud.githubusercontent.com/assets/84525/18819813/18ea68dc-834c-11e6-9b51-88fa1f2e2768.png">

The unresolved reference annotator should not provide the 'add import' quickfix for the `foobar` identifier.

@durkiewicz please assign this to me.

**Comment by durkiewicz** [comment]
@klazuka Can we close it or do you plan to do anything else with it?

**Comment by klazuka** [comment]
Done, pending release.
