### ISSUE TITLE
Feature Request: Project Structure

### ISSUE THREAD

**Issue by mcampbell** [durkiewicz/elm-plugin#35]
The "Structure" pane shows nothing in my project.  Is this user error, or does such a thing not yet exist?

If not, I'd like to add a request for this.

**Comment by klazuka** [comment]
It doesn't exist yet. Just need to do the integration work. (it's been on my wish list, too)

**Comment by klazuka** [comment]
This has been implemented now. It will be in the next release.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
