### ISSUE TITLE
Live Templates

### ISSUE THREAD

**Issue by nojaf** [durkiewicz/elm-plugin#38]
It be cool if we could create Elm live templates.

**Comment by durkiewicz** [comment]
Do you know what needs to be done to support live templates in a custom language?

**Comment by nojaf** [comment]
Uhm I believe Elm needs to be picked up as a language inside the live template editor.

**Comment by nojaf** [comment]
I can't link ![](https://i.imgur.com/qqUe4iv.png) to Elm files unless I configure it for all files.

**Comment by ianp** [comment]
@nojaf I have this set up and working locally, are there any templates that you'd like to see there by default? I'll bundle them up and prepare a PR.

**Comment by nojaf** [comment]
Well on top of my hat I was thinking

**tam**
```elm
type alias Model = 
 { }
```

**empty**

```elm
import Html exposing (Html, div, text, program)

type alias Model =
    String


init : ( Model, Cmd Msg )
init =
    ( "Hello", Cmd.none )
    
type Msg
    = NoOp
    
view : Model -> Html Msg
view model =
    div []
        [ text model ]
        
update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        NoOp ->
            ( model, Cmd.none )
            
subscriptions : Model -> Sub Msg
subscriptions model =
    Sub.none
    
main : Program Never Model Msg
main =
    program
        { init = init
        , view = view
        , update = update
        , subscriptions = subscriptions
        }
```

**mcm**
```elm
( Model, Cmd Msg)
```

**cn**
```elm
Cmd.none
```

**let**

```elm
let
    $cursor$
in
     
```

And then I was thinking regarding the html elements

Say **div**

```elm
div [] []
```

**bsinput**
```elm
div [ class "form-group" ]
            [ label [] [ text "My label" ]
            , input [ type_ "text", class "form-control" ] []
            ]
```

I'd like to add new ones as I progress in my application.

**Comment by ianp** [comment]
Yeah, most of those seem like a good add. I think that for the bootstrap stuff a better approach (and the one that I use) is to define helper functions in the project. And the empty file one is better handled as a `CreateFileAction` (which I'll look into adding).

**Comment by klazuka** [comment]
Of the examples provided above, the `let/in` one seems most compelling. A snippet for `case/of` would also be useful.
