### ISSUE TITLE
Testing 0.6.1 plugin

### ISSUE THREAD

**Issue by durkiewicz** [durkiewicz/elm-plugin#42]
There are some bugs fixed so I would like to release a new version. Before I do that, I would like a few people to install it and use it for a couple of days. If you often use Elm with IntelliJ then your help with testing is welcome.

The package is here:
https://github.com/durkiewicz/elm-plugin/raw/gh-pages/releases/elm-0.17.0_plugin-0.6.1.jar

**Comment by bgourlie** [comment]
Installing now.  I'll let ya know how it goes.

**Comment by klazuka** [comment]
I tried out the basics and it seems be working well. I did a bunch of ad-hoc testing by cmd-clicking around from the various types of references to definitions—no problems.

**Comment by bgourlie** [comment]
I haven't found any regressions using this version of the plugin.  Lookin good.

**Comment by durkiewicz** [comment]
Thank you for your help. The new version has been released.
