### ISSUE TITLE
String literal occasional parsing issue

### ISSUE THREAD

**Issue by bgourlie** [durkiewicz/elm-plugin#44]
I encountered this bug while testing the latest unstable release (issue #42), but I've noticed it in the current stable release as well.

Occasionally, while typing a string literal, the editor incorrectly displays red-squigglies:

<img width="668" alt="screen shot 2016-11-05 at 5 19 20 pm" src="https://cloud.githubusercontent.com/assets/996556/20033973/aec5e05c-a37c-11e6-9b6f-5e879d377644.png">
 
I don't have exact reproduction steps yet, but will reply here when I do.

**Comment by hm1rafael** [comment]
I'm having the same problem with classList

**Comment by mordrax** [comment]
I've noticed this too, the problem seems to go away after running elm-format or a make or just closing/opening the file.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
