### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by nitingupta910** [durkiewicz/elm-plugin#46]
I followed all steps in README but when I finally build it using: Build -> Make Project, I always get:

  `All files are up-to-date`

I even added errors to some source file but still I get this all files up-to-date on build. So, how to really build this plugin?

**Comment by durkiewicz** [comment]
I used to have some issues with building plugins in IntelliJ but never had the issue that you have so I am not able to help.

**Comment by slidemonk** [comment]
I finally go elm-plugin to compile as follows:
- Create a new plugin project
- Add elm-plugin as a module by importing elm-plugin.iml (already included in git repo root)
- Run generators on bnf and flex file as specified in README.md
- Compile elm-plugin module

**Comment by nitingupta910** [comment]
I finally go elm-plugin to compile as follows:
- Create a new plugin project
- Add elm-plugin as a module by importing elm-plugin.iml (already included in git repo root)
- Run generators on bnf and flex file as specified in README.md
- Compile elm-plugin module

**Comment by d3xter** [comment]
This should be mentioned in the README.

I've been tinkering around for an hour until i found this by accident.
