### ISSUE TITLE
Correct auto indentation

### ISSUE THREAD

**Issue by zummenix** [durkiewicz/elm-plugin#49]
In almost all cases when I'm typing the auto indentation is wrong.
For example:
```
inc : Int -> Int
inc n =
<caret>
```
expected:
```
inc : Int -> Int
inc n =
    <caret>
```

For `if then else` and `case of` expressions it also doesn't work as expected.

**Comment by mordrax** [comment]
@zummenix not sure if you're aware, but the community standard is to use https://github.com/avh4/elm-format
There is instructions in the repo to have it format on save and afaik, this is going to be merged into elm core in the coming versions.

**Comment by zummenix** [comment]
@mordrax I use elm-format and absolutely love it. I'm not sure how elm-format can help with indentation when you fast typing in the IDE.

**Comment by mordrax** [comment]
I assign it to a shortcut, so just type whatever and hit Ctrl+B, F for format, Ctrl+B, B for build, Ctrl+B, D for build `--debug`

**Comment by BinaryHexer** [comment]
It would be better if elm-format is integrated into this plugin and set to execute at save (or auto-save if you have that enabled).

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
