### ISSUE TITLE
How to Build

### ISSUE THREAD

**Issue by Namek** [durkiewicz/elm-plugin#50]
Hi! First of all, thanks for your effort on this plugin!

I went with `Building from sources` instruction but couldn't get the final step. How do I actually build the `*.jar` file here?

**Comment by klazuka** [comment]
Generating the jar is only necessary for distribution. After doing the code-generation from the `.bnf` and `.flex` files, you should just be able to `ctrl+r`.

However, if that doesn't work, maybe you don't have the IntelliJ plugin SDK setup correctly (it's kinda complicated, and the [Jetbrains docs](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html) aren't very clear).
