### ISSUE TITLE
False import error

### ISSUE THREAD

**Issue by MoonlightOwl** [durkiewicz/elm-plugin#56]
For some reason this line gives an error "Cannot find module Material.Helpers":
`import Material.Helpers exposing (map1st, map2nd)`

(I use https://github.com/debois/elm-mdl library in my project).

Nevertheless, compilation is successfull, and the code runs well, so this is not a real error.

**Comment by ccapndave** [comment]
I also experience this with various imports.  Could it be that "source-directories" is not respected in elm-package.json?

**Comment by camiel** [comment]
I think this is caused by the `effect` function in the Material.Helpers module, which seems to be a keyword in  https://github.com/durkiewicz/elm-plugin/blob/master/src/main/java/org/elmlang/intellijplugin/Elm.flex#L74.

**Comment by durkiewicz** [comment]
In this case it's similar to this issue: https://github.com/durkiewicz/elm-plugin/issues/31
