### ISSUE TITLE
Excluding webgl shader code

### ISSUE THREAD

**Issue by francisdb** [durkiewicz/elm-plugin#57]
First of all thanks for this great plugin!

It seems that the plugin can't handle shader code between `[glsl|` and `|]`. Marking everything with  errors.

![image](https://cloud.githubusercontent.com/assets/161305/23104715/67cebd7c-f6d3-11e6-8ae6-703cddab52db.png)

I guess it would not be too much work to ignore those blocks.
Even better would be to enable https://plugins.jetbrains.com/idea/plugin/6993-glsl-support if installed? But I guess that will not be a simple undertaking?

**Comment by durkiewicz** [comment]
Thanks for feedback. Can you give me more information about this syntax? Is embedding external language code a standard feature of Elm compiler? What languages can you embed into Elm? Where can I find some documentation about it?

**Comment by francisdb** [comment]
No idea, all I know is that code between `[glsl|` and `|]` should be excluded. Maybe @w0rm can shed some light on this?

**Comment by w0rm** [comment]
`[glsl|  |]` is a valid Elm code, that is supported by the elm compiler, it should be syntax highlighted as glsl language.

**Comment by francisdb** [comment]
@w0rm is this a generic thing where `[javascript| ... |]` could also be implemented by some library?

**Comment by w0rm** [comment]
@francisdb no, its not generic. The Elm compiler has the glsl parser baked in for the WebGL stuff.

**Comment by francisdb** [comment]
thanks @w0rm , @durkiewicz do you know enough with this answer?

**Comment by durkiewicz** [comment]
Ok, so now I know that I can use GLSL code as expressions in Elm code. Are there some restrictions to that?
Can I, for example, write:
```elm
f x =
    case x of
        A -> 1
        B -> [glsl| ... |] + 5
```
Or is it limited to defining the whole body of a function?
Can I use GLSL code as a non-expression code? If so, can you give me a complete list of allowed usages?

**Comment by durkiewicz** [comment]
IntelliJ has a feature of language injection: https://www.jetbrains.com/help/idea/2016.3/using-language-injections.html
So if I make sure that the content of `[glsl| ... |]` is parsed as a string in Elm plugin then you should probably be able to use the feature of language injection in order to use GLSL tooling.

**Comment by francisdb** [comment]
Just tried some things:

```elm
    let
        foo =
            [glsl|
             attribute vec3 position;
             |]

        bar =
            foo + 1
```

defining foo works, of course adding 1 fails

```
The left argument of (+) is causing a type mismatch.

149|             foo + 1
                 ^^^
(+) is expecting the left argument to be a:

    number

But the left argument is:

    Shader { a | position : Vec3 } b {}
```

**Comment by francisdb** [comment]
Thanks for taking care of this @durkiewicz ! 🙌
