### ISSUE TITLE
Parser fails on valid function name

### ISSUE THREAD

**Issue by bgourlie** [durkiewicz/elm-plugin#58]
Steps to reproduce:

    (|.) : String
    (|.) =
        "foo"

Result:

![elm-parse-error](https://cloud.githubusercontent.com/assets/996556/23564605/264d6ee8-0010-11e7-96b6-79b0b8bfc17d.PNG)

This breaks some imports, in particular elm-tools/parser

**Comment by durkiewicz** [comment]
Thanks for reporting. I'll try to fix that soon as it shouldn't be difficult. By the way: perfect example of a meaningful function name :-/

**Comment by bgourlie** [comment]
Yeah, this function in particular is part of the parser's DSL. In that context at least, it makes sense.

**Comment by camiel** [comment]
I'm having a similar issue when I open files of the elm-mdl package where a function exists called `effect`:

![effect](https://cloud.githubusercontent.com/assets/1197004/23591114/a79f7216-01eb-11e7-9742-4d8635ac1919.png)
