### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by ericbmerritt** [durkiewicz/elm-plugin#59]
Thanks for your efforts. I am normally an emacs user but I have a set of projects that I use intellij for. One of those projects is an elm project so I thought I would try out this plugin. I can't figure out how to get started. There doesn't seem to be any ability to create or import an elm project. I can import an empty project and edit the elm files, but the plugin seems to be confused about finding my elm-package.json and the various dependencies. 

So my question is, how do I actually use this plugin? What am I missing?

**Comment by klazuka** [comment]
@ericbmerritt the plugin does not try to find/read `elm-package.json`. However, it's important that you have IntelliJ treat the `elm-stuff` directory (where all your dependencies live) as a Source Set. Do not exclude it.

There's no special process for importing. It should just work (assuming that you take care of `elm-stuff` as described above).

**Comment by ericbmerritt** [comment]
So just to be clear. 

1. Set up an empty project
2. Go into Project Settings and create a module, ensure that the source set includes the 'elm-stuff' directory

Is that it?

**Comment by klazuka** [comment]
Yes. Although I've never started from an empty project before. I already had an Elm project, and I just opened it using IntelliJ. You shouldn't need to do anything special.

Another thing you might want to check is whether you have 2 Elm IntelliJ plugins installed. There's an older Elm plugin floating around out there for IntelliJ, and the names are very similar. So make sure you don't have that other one installed.

**Comment by qeepy** [comment]
Created an empty project. Tried to add module. No elm option. Elm is listed as a plugin, but I seem unable to find properties, like path to elm installation... What am I doing wrong?

**Comment by lambdaofgod** [comment]
Hey guys. I've created [this basic  how-to](https://github.com/lambdaofgod/elm-from-scratch) . Is it right? 

Do you have any other features, like compiling from IDEA?

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
