### ISSUE TITLE
Parsing issue with case in a let

### ISSUE THREAD

**Issue by jdunruh** [durkiewicz/elm-plugin#60]
The attached file compiles, but the Elm plugin shows an error. Being new to Elm, I may have done something that isn't good practice, but if it compiles and runs, it should either be OK or a warning.
[Main.txt](https://github.com/durkiewicz/elm-plugin/files/908336/Main.txt)

**Comment by bgourlie** [comment]
Would you be able to attach a screenshot that shows what specifically is parsing wrong?

**Comment by jdunruh** [comment]
![screen shot 2017-04-09 at 6 38 10 pm](https://cloud.githubusercontent.com/assets/187354/24842360/00f45dc6-1d54-11e7-8473-2cee4f6b6257.png)

**Comment by jdunruh** [comment]
Here is the requested screenshot. You should have attached code from when I opened the issue.
