### ISSUE TITLE
Feature request: parameter names

### ISSUE THREAD

**Issue by ccapndave** [durkiewicz/elm-plugin#61]
This is possibly one for the future once Elm has a more easily queryable IDE server, but the Symfony 2 plugin for IntelliJ has recently started to add in greyed out hints telling you the names of parameters.  I imagine that if this could be done for Elm it would be super helpful!

It looks like this:

<img width="586" alt="screen shot 2017-04-20 at 10 02 44" src="https://cloud.githubusercontent.com/assets/297992/25220004/ad79ec28-25b0-11e7-9534-8ce321e63b0d.png">

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
