### ISSUE TITLE
type alias doesn't find constructors

### ISSUE THREAD

**Issue by drathier** [durkiewicz/elm-plugin#62]
```
module A exposing ( T(X,Y) )
import B exposing (T(X,Y))

type alias T = B.T
```
along with 
```
moduel B exposing (T)

type T = X | Y
```

It gives me an error, claiming it cannot find `X` and `Y` in module `B`. It offers to import it for me, and if I let it import `Y`, it changes 
```
import B exposing (T(X,Y))
```
to
```
import B exposing (T(X,Y,Y))
```
adding what you ask it to import, even though it's already imported.

I'm running version 0.7.2 on PyCharm 2017.1.1

**Comment by durkiewicz** [comment]
Thank you for submitting the error. I'll try to fix it when I have some free time.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
