### ISSUE TITLE
Execute elm-make on save

### ISSUE THREAD

**Issue by jlagerweij** [durkiewicz/elm-plugin#67]
I have forked your code and created a pull request which executes elm-make for the changed files when saving them to disk. The error output from elm-make is used to annotate the file in the editor and add problems in IntelliJ. When hovering the annotations you will see the error output elm-make would also show.

I have also created a settings page where the elm-make can be enabled (It's disabled by default) and the location of the elm-make binary can be selected.

Would you be willing to include this functionality?

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
