### ISSUE TITLE
Elm-Project type

### ISSUE THREAD

**Issue by d3xter** [durkiewicz/elm-plugin#70]
It would be nice to be able to create an "Elm-Project" or import an existing one
without the need to create an empty project and add a dummy-module.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
