### ISSUE TITLE
Code Style Entry

### ISSUE THREAD

**Issue by michaelvashchinsky** [durkiewicz/elm-plugin#71]
Hello, and thank you so much for the plugin!

It would be nice to have an entry for Elm in `Preferences/Editor/Code Style`.

I have most of the languages set to use tabs and for those that are not under `Code Style`, I use `Other File Types`, which breaks Elm code by using tabs there.

Thank you in advance.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
