### ISSUE TITLE
Option to highlight used functions inside element definitions

### ISSUE THREAD

**Issue by Serfenia** [durkiewicz/elm-plugin#73]
Hi, I'd like the option to better highlight used functions in element definitions

For example:
```
someStringToUpper str =
     String.toUpper str

view model
     h1 [] [ text (someStringToUpper "Hello") ]
```

The function 'someStringToUpper' I want hightlighted. Now it has the same text color as 'text' or 'h1'.

**Comment by boxed** [comment]
But text and h1 are also functions?

**Comment by Serfenia** [comment]
@boxed That's true, but what I mean is self-defined functions and not mark-up functions.

**Comment by boxed** [comment]
So... you want highlighting based on if it's an imported function? Or just if it's imported from Html?

**Comment by Serfenia** [comment]
All in all a difference between imported functions or self-defined ones.

**Comment by boxed** [comment]
"Self defined"? As in same module? Or things not in elm-packages.json?

**Comment by Serfenia** [comment]
@boxed in the same module :)

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
