### ISSUE TITLE
Feature: syntax highlight currying

### ISSUE THREAD

**Issue by boxed** [durkiewicz/elm-plugin#74]
Something that bites me in Elm a lot is currying. I accidentally don't supply enough arguments and I get a type error (often HUGE) somewhere far from the mistake.

If you could have syntax highlighting for when functions don't have all their parameters that would be great!

**Comment by klazuka** [comment]
I don't see how this is a problem with currying specifically? Providing the wrong number of arguments can also happen when trying to use a function "normally". And as far as I remember, every time I've made this mistake, the Elm compiler has given a good error saying "maybe you are missing an argument". 

If the compiler is reporting the type error far away from the problem, and you can reduce it down to a simple example, then maybe you can add it to the [compiler's error message catalog](https://github.com/elm-lang/error-message-catalog) so that it can be fixed for all Elm users, regardless of development environment.

**Comment by boxed** [comment]
> I don't see how this is a problem with currying specifically? Providing the wrong number of arguments can also happen when trying to use a function "normally".
> 
It's a problem with currying because in many other languages partial application is explicit so never accidentally create a new function when you wanted a value. 

> And as far as I remember, every time I've made this mistake, the Elm compiler has given a good error saying "maybe you are missing an argument".
> 
That has happened to me for sure and that's nice but it's far from every time. 
> If the compiler is reporting the type error far away from the problem, and you can reduce it down to a simple example, then maybe you can add it to the compiler's error message catalog so that it can be fixed for all Elm users, regardless of development environment.
> 
The type error is shown as close to the /type error/ as possible as far as I can see. The problem is that my mistake created a type error that isn't caught until it hits something where I've made a type declaration. This is also the reason I almost never use inferred types because that pushes the error message further away.

Personally I think implicit partial evaluation should be removed from Elm and that's the fix for the language but I think that's pretty unlikely. But if I can /see/ partial evaluation in any way that's fine, I don't need to see it in the text of the code normally.

**Comment by klazuka** [comment]
Implicit currying and partial application is a core feature of the ML family of languages. It does take some getting used to when coming from other languages.

Would running elm-make as an [external annotator](https://github.com/durkiewicz/elm-plugin/pull/68) make this easier for you? Maybe part of the pain is that (currently) compile errors are reported in a separate window instead of as red underlines on the source code in the editor.

**Comment by boxed** [comment]
Nope, this wouldn't solve the problem. In fact there are two quite distinct problems:

1. Errors that are annoying and hard to handle. I just got one now for example:

```
unction `program` is expecting the argument to be:

    { ..., view : Model -> Html Msg }

But it is:

    { ...
    , view :
          (
          Msg
          -> { currentText : String
          , inputId : String
          , items : List Item
          , listControl : ListControl.Model String
          , showListControl : Bool
          }
          )
          -> Model
          -> Html
                 { currentText : String
                 , inputId : String
                 , items : List Item
                 , listControl : ListControl.Model String
                 , showListControl : Bool
                 }
    }

Hint: Problem in the `view` field. It looks like a function needs 1 more
argument.
```

It's pretty bad. It just tells you there's a mistake on a function somewhere inside view. And if your view calls other view functions that don't have proper type annotations the problem can be in any of those too. I don't think this actually can be fixed by the error message being improved. 

2. Yes, it takes some getting used to to use currying, but I think I'm fairly used to it since I do type those without thinking much quite a bit. So I don't think it's that. I just want to see if I did what I wanted to do. Just having a way to syntax highlight when an expression ends up as curried would be great.

**Comment by shamansir** [comment]
I think there is a number of cases where I, as a developer, intentionally not specify all the arguments when I call the function — currying helps to postpone things for later calls and manage the program flow in an easy and elegant ways. So, in these cases, there is totally no error for me in having an insufficient number of arguments, so why should it be marked as such?

**Comment by boxed** [comment]
@shamansir you misunderstand. I don’t want it marked as an error. Just a color or effect I choose. Like a string or a keyword. I just want to see what the code means.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
