### ISSUE TITLE
ignores semantic highlighting 

### ISSUE THREAD

**Issue by StandardNerd** [durkiewicz/elm-plugin#75]
When Semantic Highlighting (Editor->Colors&Fonts->Language Defaults->Semantic highlighting) is checked, then each parameter and local variable should be coloured.

Actual state: Elm-plugin ignores Semantic highlighting.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
