### ISSUE TITLE
Integration with elm-analyse?

### ISSUE THREAD

**Issue by r-k-b** [durkiewicz/elm-plugin#77]
[elm-analyse](https://github.com/stil4m/elm-analyse):
> A tool that allows you to analyse your Elm code, identify deficiencies and apply best practices.

It's great on it's own, but would it be a good idea to have that functionality within the IDE?

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
