### ISSUE TITLE
Elm v0.17.0

### ISSUE THREAD

**Issue by mickeyvip** [durkiewicz/elm-plugin#8]
Hello, 

Can you please update the plugin to support Elm `0.17.0`?

For example:
![image](https://cloud.githubusercontent.com/assets/220427/15275599/ca45011e-1ad8-11e6-95c1-6335ac0c1e7c.png)

Thank you.

**Comment by durkiewicz** [comment]
I'll try to find some time to do it in a week or two.

**Comment by durkiewicz** [comment]
I did some changes to support Elm 0.17 and it's already in JetBrains' plugins repository.

**Comment by mickeyvip** [comment]
Cool! Thanks!
