### ISSUE TITLE
Odd Private Use Area Unicode character left over when reopening a file

### ISSUE THREAD

**Issue by andrew-silvernail** [durkiewicz/elm-plugin#80]
I get a weird unicode character when reopening an Elm file sometimes.
<img width="696" alt="screen shot 2018-04-29 at 8 33 32 pm" src="https://user-images.githubusercontent.com/528268/39937737-87502348-5505-11e8-99ca-952484c8a82d.png">
<img width="1141" alt="screen shot 2018-04-29 at 8 33 52 pm" src="https://user-images.githubusercontent.com/528268/39937739-87731344-5505-11e8-964b-0dbf66354a59.png">

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
