### ISSUE TITLE
Maintenance mode?

### ISSUE THREAD

**Issue by klazuka** [durkiewicz/elm-plugin#82]
Hi @durkiewicz . With Elm 0.19 coming out soon (hopefully), I was wondering what you were going to do with respect to this plugin? Based on previous discussion, it doesn't sound like you will be adding 0.19 support, in which case would you mind putting something in the Readme directing users to my version of the plugin.

Thanks again for all the work you've done.

**Comment by durkiewicz** [comment]
I don't know what is going to be in Elm 0.19, so I cannot estimate an effort of adjusting the plugin. I also have not tried your plugin yet so I do not know if it provides everything that this plugin provides.

I know that Elm 0.19 is going to have one critical compilation performance improvement which might be a game changer from my point of view so I do not exclude a possibility of going back to Elm and to active development of the plugin.

As you see, I cannot make such a decision yet for multiple reasons.

**Comment by klazuka** [comment]
@durkiewicz Elm 0.19 is [out now](https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md)

**Comment by durkiewicz** [comment]
Hi Keith,

I've finally made a decision to give up. Thank you for your valuable help in developing some features of the plugin. I've put your plugin as a suggestion in the README file - good luck with development!

This plugin is also requested to be removed from IntelliJ's plugin repository so users will have to switch to your one.

**Comment by amcsi** [comment]
@durkiewicz hey thanks for working on this project initially. If you hadn't made this project initially, I probably would not have gone into trying out Elm :)

**Comment by klazuka** [comment]
@durkiewicz thanks. Just like @amcsi, without your plugin I probably wouldn't have been able to get the rest of my team to use Elm (we all use IntelliJ heavily for the rest of our work). And as someone who has now implemented one of these IntelliJ plugins, I know how much work it is 😄

**Comment by bgourlie** [comment]
@durkiewicz Just wanted to chime in and say thank you for the effort with this plugin, and also a thank you to @klazuka for his continued development. I'm very appreciative of the work both of you have put in.
